import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import "./theme-variables.css";
import { cookies } from "next/headers";
import ClientThemeProvider from "./components/client-theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const themeCookie = cookieStore.get('theme');
  const theme = themeCookie?.value || 'light';

  return (
    <html lang="en" className={theme === 'dark' ? 'dark' : 'light'}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ClientThemeProvider initialTheme={theme as 'light' | 'dark'}>
          {children}
        </ClientThemeProvider>
      </body>
    </html>
  );
}
